version: "3.1"

services:

  db:
    container_name: db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=t3kit
      - MYSQL_USER=t3kit
      - MYSQL_PASSWORD=t3kit1234
    restart: always

  web:
    container_name: web
    image: t3kit/ubuntu16-php7-apache:0.0.1
    ports:
      - "8888:80"
    depends_on:
      - db
      - t3kit_solr
    volumes:
      - ./docker_conf:/docker_conf
      - ./vendor/t3kit/db:/t3kit_db
      - t3kit-sync:/var/www/html:rw
    restart: always
    command: "sh /docker_conf/macos/run.sh"

  t3kit_solr:
    container_name: t3kit_solr
    image: typo3solr/ext-solr:6.0.0
    ports:
      - "8983:8983"
    volumes:
      - $PWD/solrdata:/opt/solr/server/solr/data/
    restart: always

volumes:
  t3kit-sync:
    external: true
