# Load default processing options
imports:
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }

# Add configuration for the editor
# https://ckeditor.com/latest/samples/toolbarconfigurator/index.html#basic
# For complete documentation see http://docs.ckeditor.com/#!/api/CKEDITOR.config
editor:
  config:

    format_tags: "p;h1;h2;h3;h4;h5;pre"

    toolbarGroups:
        - { name: 'styles', groups: [ styles ] }
        - { name: 'basicstyles', groups: [ basicstyles] }
        - { name: paragraph, groups: [ list, indent, blocks, align ] }
        - { name: 'links', groups: [ links ] }
        - { name: clipboard, groups: [ clipboard, cleanup, undo ] }
        - { name: 'insert', groups: [ insert, insertcharacters ] }
        - { name: 'tools', groups: [ tools ] }
        - { name: 'document', groups: [ mode ] }

    justifyClasses:
      - text-left
      - text-center
      - text-right

    extraPlugins:
      - justify
      - autolink
      - wordcount

    removePlugins:
      - image

    removeButtons:
      - JustifyBlock
      - Anchor
      - Table
