<?php
# PackageStates.php

# This file is maintained by TYPO3's package management. Although you can edit it
# manually, you should rather use the extension manager for maintaining packages.
# This file will be regenerated automatically if it doesn't exist. Deleting this file
# should, however, never become necessary if you use the package commands.

return [
    'packages' => [
        'core' => [
            'composerName' => 'typo3/cms-core',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/core/',
            'suggestions' => [],
        ],
        'extbase' => [
            'composerName' => 'typo3/cms-extbase',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/extbase/',
            'suggestions' => [],
        ],
        'fluid' => [
            'composerName' => 'typo3/cms-fluid',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/fluid/',
            'suggestions' => [],
        ],
        'documentation' => [
            'composerName' => 'typo3/cms-documentation',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/documentation/',
            'suggestions' => [],
        ],
        'info' => [
            'composerName' => 'typo3/cms-info',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/info/',
            'suggestions' => [],
        ],
        'info_pagetsconfig' => [
            'composerName' => 'typo3/cms-info-pagetsconfig',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/info_pagetsconfig/',
            'suggestions' => [],
        ],
        'extensionmanager' => [
            'composerName' => 'typo3/cms-extensionmanager',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/extensionmanager/',
            'suggestions' => [],
        ],
        'lang' => [
            'composerName' => 'typo3/cms-lang',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/lang/',
            'suggestions' => [],
        ],
        'setup' => [
            'composerName' => 'typo3/cms-setup',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/setup/',
            'suggestions' => [],
        ],
        'rtehtmlarea' => [
            'composerName' => 'typo3/cms-rtehtmlarea',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/rtehtmlarea/',
            'suggestions' => [
                'setup',
            ],
        ],
        'rsaauth' => [
            'composerName' => 'typo3/cms-rsaauth',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/rsaauth/',
            'suggestions' => [],
        ],
        'saltedpasswords' => [
            'composerName' => 'typo3/cms-saltedpasswords',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/saltedpasswords/',
            'suggestions' => [
                'rsaauth',
            ],
        ],
        'func' => [
            'composerName' => 'typo3/cms-func',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/func/',
            'suggestions' => [],
        ],
        'wizard_crpages' => [
            'composerName' => 'typo3/cms-wizard-crpages',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/wizard_crpages/',
            'suggestions' => [],
        ],
        'wizard_sortpages' => [
            'composerName' => 'typo3/cms-wizard-sortpages',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/wizard_sortpages/',
            'suggestions' => [],
        ],
        'about' => [
            'composerName' => 'typo3/cms-about',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/about/',
            'suggestions' => [],
        ],
        'aboutmodules' => [
            'composerName' => 'typo3/cms-aboutmodules',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/aboutmodules/',
            'suggestions' => [],
        ],
        'backend' => [
            'composerName' => 'typo3/cms-backend',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/backend/',
            'suggestions' => [],
        ],
        'belog' => [
            'composerName' => 'typo3/cms-belog',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/belog/',
            'suggestions' => [],
        ],
        'beuser' => [
            'composerName' => 'typo3/cms-beuser',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/beuser/',
            'suggestions' => [],
        ],
        'context_help' => [
            'composerName' => 'typo3/cms-context-help',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/context_help/',
            'suggestions' => [],
        ],
        'cshmanual' => [
            'composerName' => 'typo3/cms-cshmanual',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/cshmanual/',
            'suggestions' => [],
        ],
        'felogin' => [
            'composerName' => 'typo3/cms-felogin',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/felogin/',
            'suggestions' => [],
        ],
        'filelist' => [
            'composerName' => 'typo3/cms-filelist',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/filelist/',
            'suggestions' => [],
        ],
        'filemetadata' => [
            'composerName' => 'typo3/cms-filemetadata',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/filemetadata/',
            'suggestions' => [],
        ],
        'fluid_styled_content' => [
            'composerName' => 'typo3/cms-fluid-styled-content',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/fluid_styled_content/',
            'suggestions' => [],
        ],
        'form' => [
            'composerName' => 'typo3/cms-form',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/form/',
            'suggestions' => [],
        ],
        'frontend' => [
            'composerName' => 'typo3/cms-frontend',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/frontend/',
            'suggestions' => [],
        ],
        'impexp' => [
            'composerName' => 'typo3/cms-impexp',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/impexp/',
            'suggestions' => [],
        ],
        'install' => [
            'composerName' => 'typo3/cms-install',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/install/',
            'suggestions' => [],
        ],
        'lowlevel' => [
            'composerName' => 'typo3/cms-lowlevel',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/lowlevel/',
            'suggestions' => [],
        ],
        'recordlist' => [
            'composerName' => 'typo3/cms-recordlist',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/recordlist/',
            'suggestions' => [],
        ],
        'reports' => [
            'composerName' => 'typo3/cms-reports',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/reports/',
            'suggestions' => [],
        ],
        'scheduler' => [
            'composerName' => 'typo3/cms-scheduler',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/scheduler/',
            'suggestions' => [],
        ],
        'sv' => [
            'composerName' => 'typo3/cms-sv',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/sv/',
            'suggestions' => [],
        ],
        'sys_note' => [
            'composerName' => 'typo3/cms-sys-note',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/sys_note/',
            'suggestions' => [],
        ],
        't3editor' => [
            'composerName' => 'typo3/cms-t3editor',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/t3editor/',
            'suggestions' => [],
        ],
        't3skin' => [
            'composerName' => 'typo3/cms-t3skin',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/t3skin/',
            'suggestions' => [],
        ],
        'tstemplate' => [
            'composerName' => 'typo3/cms-tstemplate',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/tstemplate/',
            'suggestions' => [],
        ],
        'viewpage' => [
            'composerName' => 'typo3/cms-viewpage',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/viewpage/',
            'suggestions' => [],
        ],
        'dyncss' => [
            'composerName' => 'dyncss',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/dyncss/',
            'suggestions' => [],
        ],
        'dyncss_less' => [
            'composerName' => 'dyncss_less',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/dyncss_less/',
            'suggestions' => [],
        ],
        'static_info_tables' => [
            'composerName' => 'sjbr/static_info_tables',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/static_info_tables/',
            'suggestions' => [],
        ],
        'themes' => [
            'composerName' => 'typo3-themes/themes',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/themes/',
            'suggestions' => [],
        ],
        'gridelements' => [
            'composerName' => 'GridElementsTeam/Gridelements',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/gridelements/',
            'suggestions' => [],
        ],
        't3kit_extension_tools' => [
            'composerName' => 't3kit/t3kit-extension-tools',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/t3kit_extension_tools/',
            'suggestions' => [],
        ],
        'theme_t3kit' => [
            'composerName' => 't3kit/theme-t3kit',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/theme_t3kit/',
            'suggestions' => [],
        ],
        'theme_t3kit_bluemountain' => [
            'composerName' => 'theme_t3kit_bluemountain',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/theme_t3kit_bluemountain/',
            'suggestions' => [],
        ],
        'realurl' => [
            'composerName' => 'dmitryd/typo3-realurl',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/realurl/',
            'suggestions' => [
                'static_info_tables',
            ],
        ],
        'realurl_404_multilingual' => [
            'composerName' => 'realurl_404_multilingual',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/realurl_404_multilingual/',
            'suggestions' => [],
        ],
        'seo_basics' => [
            'composerName' => 'b13/seo_basics',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/seo_basics/',
            'suggestions' => [],
        ],
        'go_maps_ext' => [
            'composerName' => 'clickstorm/go_maps_ext',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/go_maps_ext/',
            'suggestions' => [],
        ],
        'news' => [
            'composerName' => 'georgringer/news',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/news/',
            'suggestions' => [],
        ],
        'pxa_form_enhancement' => [
            'composerName' => 'pxa_form_enhancement',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/pxa_form_enhancement/',
            'suggestions' => [],
        ],
        'pxa_newsletter_subscription' => [
            'composerName' => 'pxa_newsletter_subscription',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/pxa_newsletter_subscription/',
            'suggestions' => [],
        ],
        'solr' => [
            'composerName' => 'apache-solr-for-typo3/solr',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/solr/',
            'suggestions' => [],
        ],
        'yaml_parser' => [
            'composerName' => 'typo3-ter/yaml-parser',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/yaml_parser/',
            'suggestions' => [],
        ],
        'adodb' => [
            'composerName' => 'typo3/cms-adodb',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/adodb/',
            'suggestions' => [],
        ],
        'css_styled_content' => [
            'composerName' => 'typo3/cms-css-styled-content',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/css_styled_content/',
            'suggestions' => [],
        ],
        'dbal' => [
            'composerName' => 'typo3/cms-dbal',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/dbal/',
            'suggestions' => [],
        ],
        'feedit' => [
            'composerName' => 'typo3/cms-feedit',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/feedit/',
            'suggestions' => [],
        ],
        'indexed_search' => [
            'composerName' => 'typo3/cms-indexed-search',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/indexed_search/',
            'suggestions' => [],
        ],
        'indexed_search_mysql' => [
            'composerName' => 'typo3/cms-indexed-search-mysql',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/indexed_search_mysql/',
            'suggestions' => [],
        ],
        'linkvalidator' => [
            'composerName' => 'typo3/cms-linkvalidator',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/linkvalidator/',
            'suggestions' => [],
        ],
        'opendocs' => [
            'composerName' => 'typo3/cms-opendocs',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/opendocs/',
            'suggestions' => [],
        ],
        'recycler' => [
            'composerName' => 'typo3/cms-recycler',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/recycler/',
            'suggestions' => [],
        ],
        'sys_action' => [
            'composerName' => 'typo3/cms-sys-action',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/sys_action/',
            'suggestions' => [],
        ],
        'taskcenter' => [
            'composerName' => 'typo3/cms-taskcenter',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/taskcenter/',
            'suggestions' => [
                'sys_action',
            ],
        ],
        'version' => [
            'composerName' => 'typo3/cms-version',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/version/',
            'suggestions' => [],
        ],
        'workspaces' => [
            'composerName' => 'typo3/cms-workspaces',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/workspaces/',
            'suggestions' => [],
        ],
    ],
    'version' => 4,
];
