# ddev apache solr recipe file
#
# Adapted to t3kit requirements.

version: '3.6'

services:
  solr: # This is the service name used when running ddev commands accepting the --service flag
    container_name: ddev-${DDEV_SITENAME}-solr # This is the name of the container. It is recommended to follow the same name convention used in the main docker-compose.yml file.
    image: typo3solr/ext-solr:6.0.0
    restart: always
    ports:
      - 8983
    labels:
      # These labels ensure this service is discoverable by ddev
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
      com.ddev.app-url: $DDEV_URL
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME # This defines the host name the service should be accessible from. This will be sitename.ddev.local
      - HTTP_EXPOSE=8983 # This defines the port the service should be accessible from at sitename.ddev.local
    volumes:
      - ./solrdata:/opt/solr/server/solr/data${CACHED}

  # This links the solr service to the web service defined in the main docker-compose.yml, allowing applications running in the web service to access the solr service at sitename.ddev.local:8983
  web:
    links:
      - solr:$DDEV_HOSTNAME
